# Generated by Django 4.1.7 on 2023-02-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=60, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Comics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('published', models.DateField(verbose_name='Дата публикации')),
                ('episode', models.IntegerField(verbose_name='Серия')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('author', models.ManyToManyField(related_name='authors', to='main.author', verbose_name='автор')),
            ],
            options={
                'verbose_name': 'комикс',
                'verbose_name_plural': 'комиксы',
                'ordering': ('-published',),
            },
        ),
    ]
